on:
  push:
    branches: [ "master" ]
 
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
#define hash commit
      run: export HASHCOMMIT=`git log -1 --pretty=format:"%H"` 
#build versionized docker image
      run: docker build . --file Dockerfile --tag datagrok-test-metrics:$HASHCOMMIT
