version: "3.7"
services:
  nginx:
    image: nginx:alpine
    configs:
        - source: nginx_config
          target: /etc/nginx/nginx.conf
    ports: 
    - "5000:80"

  app1:
#    image: ksumag/datagrok-test-metrics:v1
     build: .

  app2:
 #   image: ksumag/datagrok-test-metrics:v1
     build: . 
configs:
  nginx_config:
    file: ./default.conf


