name: Docker Image CI

on:
  push:
    branches: [ "master" ]
 
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
     - name: Login to DockerHub
       uses: docker/login-action@v2
       with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
     - name: Add SHORT_SHA env property with commit short sha
       run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV
     - name: Build and push
       uses: docker/build-push-action@v3
       with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/datagrok-test-metrics:${SHORT_SHA}
